/***************************************************************
 *
 * Interactive Learning Platform: Digital Audio
 * Copyright (c) 2010 Dr. Andrew Kwok-Fai LUI
 * The Open University of Hong Kong
 *
 * Enhance the learning effectiveness of students through greater interactions
 */
/*  This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
package faifai.audio;

import javax.sound.sampled.AudioFormat;

public class QuantizationVisualiserPanel extends javax.swing.JPanel implements Runnable {

  private Thread thisThread;
  private boolean toStop = false;
  private int bitsPerSample[] = {8, 6, 4, 3, 2, 1};
  private int bitsPerSampleIndex = 0;
  private int updateDisplay = 0;
  private QuantizationProcess theProcess = null;

  /** Creates new form WaveGeneratorPanel */
  public QuantizationVisualiserPanel() {
    initComponents();
    waveDrawingLabel1.setRepeatDrawWave(true);
    waveDrawingLabel2.setRepeatDrawWave(true);
    thisThread = new Thread(this);
    thisThread.start();
    update();
  }

  public QuantizationProcess startQuantizationProcess() {
    theProcess = new QuantizationProcess();
    return theProcess;
  }

  public void update() {
    if (theProcess != null) {
      theProcess.setBitsPerSample(bitsPerSample[bitsPerSampleIndex]);
    }
    if (updateDisplay == 0) {
      jLabel1.setText("BITS PER SAMPLE: " + bitsPerSample[bitsPerSampleIndex]);
    } else if (updateDisplay == 1) {
      if (theProcess != null) {
        jLabel1.setText("QUANTIZATION LEVELS: " + (int) Math.pow(2, bitsPerSample[bitsPerSampleIndex]));
      }
    } else if (updateDisplay == 2) {
      jLabel1.setText("TIME SCALE: " + waveDrawingLabel1.getTimeScale() + "s");
    }
  }

  public void makeFiner() {
    bitsPerSampleIndex--;
    if (bitsPerSampleIndex < 0) {
      bitsPerSampleIndex = 0;
    }
    update();
  }

  public void makeCoarser() {
    bitsPerSampleIndex++;
    if (bitsPerSampleIndex >= bitsPerSample.length) {
      bitsPerSampleIndex = bitsPerSample.length - 1;
    }
    update();
  }

  public void close() {
    toStop = true;
  }

  public void run() {
    long count = 0;
    while (true) {
      if (toStop) {
        break;
      }
      if (theProcess != null) {
        AudioDataBuffer inputDataBuffer = theProcess.getInputDataBuffer();
        AudioDataBuffer outputDataBuffer = theProcess.getOutputDataBuffer();
        if (inputDataBuffer != null) {
          waveDrawingLabel1.setDataBuffer(inputDataBuffer.getDataBuffer(), inputDataBuffer.getDataLength(),
                  inputDataBuffer.getAudioFormat());
        }
        if (outputDataBuffer != null) {
          waveDrawingLabel2.setDataBuffer(outputDataBuffer.getDataBuffer(), outputDataBuffer.getDataLength(),
                  outputDataBuffer.getAudioFormat());
        }
      }
      try {
        thisThread.sleep(500);
        count++;
        if (count % 3 == 0) {
          updateDisplay = (updateDisplay + 1) % 2;
          update();
        }
      } catch (InterruptedException ex) {
        ex.printStackTrace();
        break;
      } catch (Exception ex) {
        ex.printStackTrace();
      }
    }
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    jPanel1 = new javax.swing.JPanel();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    waveDrawingLabel1 = new faifai.audio.WaveDrawingLabel();
    waveDrawingLabel2 = new faifai.audio.WaveDrawingLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();

    setBackground(new java.awt.Color(153, 0, 102));
    setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quantization Visualiser", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 11), new java.awt.Color(255, 255, 255))); // NOI18N
    setMinimumSize(new java.awt.Dimension(320, 160));
    setPreferredSize(new java.awt.Dimension(320, 160));
    setLayout(new java.awt.GridBagLayout());

    jPanel1.setMinimumSize(new java.awt.Dimension(66, 25));
    jPanel1.setOpaque(false);
    jPanel1.setPreferredSize(new java.awt.Dimension(175, 25));
    jPanel1.setLayout(new java.awt.GridBagLayout());

    jButton1.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
    jButton1.setText("Finer");
    jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    jButton1.setMargin(new java.awt.Insets(2, 0, 2, 0));
    jButton1.setMaximumSize(new java.awt.Dimension(60, 20));
    jButton1.setMinimumSize(new java.awt.Dimension(60, 20));
    jButton1.setPreferredSize(new java.awt.Dimension(60, 20));
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weighty = 1.0;
    jPanel1.add(jButton1, gridBagConstraints);

    jButton2.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
    jButton2.setText("Coarser");
    jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    jButton2.setMargin(new java.awt.Insets(2, 0, 2, 0));
    jButton2.setMaximumSize(new java.awt.Dimension(60, 20));
    jButton2.setMinimumSize(new java.awt.Dimension(60, 20));
    jButton2.setPreferredSize(new java.awt.Dimension(60, 20));
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton2ActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weighty = 1.0;
    jPanel1.add(jButton2, gridBagConstraints);

    jLabel1.setBackground(new java.awt.Color(204, 255, 0));
    jLabel1.setFont(new java.awt.Font("Monospaced", 0, 10));
    jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
    jLabel1.setOpaque(true);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    jPanel1.add(jLabel1, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
    add(jPanel1, gridBagConstraints);

    waveDrawingLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
    waveDrawingLabel1.setText("waveDrawingLabel1");
    waveDrawingLabel1.setMaximumSize(new java.awt.Dimension(96, 60));
    waveDrawingLabel1.setMinimumSize(new java.awt.Dimension(96, 60));
    waveDrawingLabel1.setPreferredSize(new java.awt.Dimension(96, 60));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    add(waveDrawingLabel1, gridBagConstraints);

    waveDrawingLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
    waveDrawingLabel2.setText("waveDrawingLabel1");
    waveDrawingLabel2.setMaximumSize(new java.awt.Dimension(96, 60));
    waveDrawingLabel2.setMinimumSize(new java.awt.Dimension(96, 60));
    waveDrawingLabel2.setPreferredSize(new java.awt.Dimension(96, 60));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    add(waveDrawingLabel2, gridBagConstraints);

    jLabel2.setForeground(new java.awt.Color(255, 255, 255));
    jLabel2.setText("Input");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    add(jLabel2, gridBagConstraints);

    jLabel3.setForeground(new java.awt.Color(255, 255, 255));
    jLabel3.setText("Output");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    add(jLabel3, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    makeFiner();
  }//GEN-LAST:event_jButton1ActionPerformed

  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    makeCoarser();
  }//GEN-LAST:event_jButton2ActionPerformed
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JPanel jPanel1;
  private faifai.audio.WaveDrawingLabel waveDrawingLabel1;
  private faifai.audio.WaveDrawingLabel waveDrawingLabel2;
  // End of variables declaration//GEN-END:variables
}
