/***************************************************************
 *
 * Interactive Learning Platform: Digital Audio
 * Copyright (c) 2010 Dr. Andrew Kwok-Fai LUI
 * The Open University of Hong Kong
 *
 * Enhance the learning effectiveness of students through greater interactions
 */
/*  This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
package faifai.audio;

public class SimpleClipPlayerPanel extends javax.swing.JPanel implements Runnable {

  private SimpleClipPlayer thePlayer = null;
  private Thread thisThread;
  private boolean toStop = false;

  /** Creates new form WaveGeneratorPanel */
  public SimpleClipPlayerPanel() {
    initComponents();
    jLabel1.setText("100%");
    thisThread = new Thread(this);
    thisThread.start();
  }

  public SimpleClipPlayer startSimplePlayer() {
    if (thePlayer == null) {
      thePlayer = new SimpleClipPlayer();
    }
    return thePlayer;
  }

  public SimpleStreamPlayer startSimpleStreamPlayer() {
    if (thePlayer == null) {
      thePlayer = new SimpleStreamPlayer();
    }
    return (SimpleStreamPlayer) thePlayer;
  }

  private void updateGain() {
    int value = jSlider1.getValue();
    double gain = (value / 100.0);
    thePlayer.setGain(gain);
    jLabel1.setText(value + "%");
  }

  public void run() {
    while (true) {
      if (toStop) {
        break;
      }
      if (thePlayer != null) {
        double level = thePlayer.getAverageLevel();
        levelLabel1.setData(level);
        levelLabel1.refresh();
      }
      try {
        thisThread.sleep(500);
      } catch (InterruptedException ex) {
        ex.printStackTrace();
        break;
      } catch (Exception ex) {
        ex.printStackTrace();
      }
    }
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    jPanel2 = new javax.swing.JPanel();
    jSlider1 = new javax.swing.JSlider();
    jLabel3 = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    levelLabel1 = new faifai.audio.LevelLabel();

    setBackground(new java.awt.Color(153, 0, 102));
    setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Audio Stream Player", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 11), new java.awt.Color(255, 255, 255))); // NOI18N
    setLayout(new java.awt.GridBagLayout());

    jPanel2.setOpaque(false);
    jPanel2.setLayout(new java.awt.GridBagLayout());

    jSlider1.setBackground(new java.awt.Color(102, 102, 102));
    jSlider1.setForeground(new java.awt.Color(51, 51, 51));
    jSlider1.setToolTipText("Frequency");
    jSlider1.setValue(100);
    jSlider1.setOpaque(false);
    jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        jSlider1StateChanged(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    jPanel2.add(jSlider1, gridBagConstraints);

    jLabel3.setFont(new java.awt.Font("Tahoma", 3, 9));
    jLabel3.setForeground(new java.awt.Color(255, 255, 255));
    jLabel3.setText("GAIN");
    jLabel3.setMinimumSize(new java.awt.Dimension(30, 15));
    jLabel3.setPreferredSize(new java.awt.Dimension(30, 15));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    jPanel2.add(jLabel3, gridBagConstraints);

    jLabel1.setBackground(new java.awt.Color(204, 255, 51));
    jLabel1.setFont(new java.awt.Font("Monospaced", 0, 10));
    jLabel1.setForeground(new java.awt.Color(51, 51, 51));
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
    jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
    jLabel1.setMaximumSize(new java.awt.Dimension(38, 20));
    jLabel1.setMinimumSize(new java.awt.Dimension(38, 20));
    jLabel1.setOpaque(true);
    jLabel1.setPreferredSize(new java.awt.Dimension(38, 20));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
    gridBagConstraints.weighty = 1.0;
    jPanel2.add(jLabel1, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
    add(jPanel2, gridBagConstraints);

    levelLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
    levelLabel1.setText("levelLabel1");
    levelLabel1.setMaximumSize(new java.awt.Dimension(53, 25));
    levelLabel1.setMinimumSize(new java.awt.Dimension(53, 25));
    levelLabel1.setPreferredSize(new java.awt.Dimension(53, 25));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    add(levelLabel1, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents

  private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
    updateGain();
  }//GEN-LAST:event_jSlider1StateChanged
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JSlider jSlider1;
  private faifai.audio.LevelLabel levelLabel1;
  // End of variables declaration//GEN-END:variables
}
